#ifndef DEFINE_H_INCLUDED
#define DEFINE_H_INCLUDED

#define BLOCS_SIZE 32

#define NB_BLOCS_L 100
#define NB_BLOCS_H 100

#define NB_BLOCS_X 11*(64/BLOCS_SIZE)
#define NB_BLOCS_Y 9*(64/BLOCS_SIZE)

#define DIST_FROM_UP ((NB_BLOCS_Y-1)/2)+1
#define DIST_FROM_LEFT ((NB_BLOCS_X-1)/2)+1

#endif // DEFINE_H_INCLUDED
